### ISSUE TITLE
No longer available in Sublime Package Control

### ISSUE THREAD

**Issue by ckumar1** [leonid-shevtsov/GemLinks_SublimeText#1]
This doesn't appear to be available through the official package control anymore. Only by manually installing it. Hopefully you'll be able to get it back on there!

https://packagecontrol.io/search/gem%20links

**Comment by leonid-shevtsov** [comment]
It wasn't ever in Package Control because there was already a package that had some of the features (namely, opening the gem folder). But years have passed since then. Maybe I should try again. :)
